version: '3.8'

services:
  app:
    build: .
    # ports: # Комментируем, так как доступ будет через Nginx на порту 80
    #   - "3000:3000"
    expose:
      - "3000" # Оставляем expose для связи с Nginx
    depends_on:
      - mongo
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/roulette
      - ADMIN_PASSWORD=admin123
    volumes:
      - ./src:/app/src
      # При необходимости можно монтировать public и media для разработки без пересборки контейнера app
      # - ./public:/app/public 
      # - ./media:/app/media
    restart: unless-stopped

  mongo:
    image: mongo:6
    ports: # Оставляем для возможного доступа к БД извне
      - "27017:27017"
    volumes:
      - roulette-data:/data/db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80" # Маппим порт 80 хоста на порт 80 контейнера Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Монтируем нашу конфигурацию
    depends_on:
      - app # Nginx должен стартовать после приложения
    restart: unless-stopped

volumes:
  roulette-data: 