version: '3.8'

services:
  app:
    build: .
    # ports: # Комментируем, так как доступ будет через Nginx на порту 80
    #   - "3000:3000"
    expose:
      - "3000" # Оставляем expose для связи с Nginx
    depends_on:
      - mongo
    environment:
      - PORT=3000
      # Обновляем URI для включения аутентификации (замените user:password!)
      - MONGODB_URI=mongodb://mongoUser:mongoPassword@mongo:27017/roulette?authSource=admin
      - ADMIN_PASSWORD=admin123
    volumes:
      - ./src:/app/src
      # При необходимости можно монтировать public и media для разработки без пересборки контейнера app
      # - ./public:/app/public 
      # - ./media:/app/media
    restart: unless-stopped

  mongo:
    image: mongo:6
    # ports: # Удаляем или комментируем эту секцию! Порт не должен быть доступен извне.
    #   - "27017:27017"
    environment:
      # Задаем пользователя и пароль для MongoDB
      - MONGO_INITDB_ROOT_USERNAME=mongoUser # Замените на свое имя пользователя
      - MONGO_INITDB_ROOT_PASSWORD=mongoPassword # Замените на свой пароль
    volumes:
      - roulette-data:/data/db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80" # Маппим порт 80 хоста на порт 80 контейнера Nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf # Монтируем нашу конфигурацию
    depends_on:
      - app # Nginx должен стартовать после приложения
    restart: unless-stopped

volumes:
  roulette-data: 